### ISSUE TITLE
Formatting of help output ugly when using "long" command names

### ISSUE THREAD

**Issue by selmaohneh** [nerai/CMenu#101]
` var menu = new CMenu();
            menu.Add("helloworld", _ => SayHelloWorld(), "Says hello world.");
            menu.Add("greet", x => Greet(x), "Greets with a name.");
            menu.Run();`

When firing `help` the formatting is not correct. It should be dependend on the longest command name instead of a hardcoded padding of (i guess) 4 spaces.

Available commands:
g   | greet
hell | helloworld
      help
q   | quit
Type "help <command>" for individual command help.

**Comment by nerai** [comment]
Thanks for the report. It should be solved in the current dev branch: https://github.com/nerai/NConsoleMenu/tree/0.9/dev

**Comment by selmaohneh** [comment]
Thanks! Let me know or close the issue, when you merge it / update nuget.

**Comment by nerai** [comment]
@selmaohneh Actually, I don't have access to my Nuget infrastructure at the moment. So we're stuck with the master branch for now.
