### ISSUE TITLE
Replace all Console.X

### ISSUE THREAD

**Issue by shargon** [nerai/CMenu#56]
Replace all Console.Write , Console.Read, Console.XXXX with interface like this

public interface IConsole
{
      void WrilteLine(string line);
      string ReadLine();
      void SetForegroundColor(ConsoleColor color);
}

And implement ConsoleInterface , this make possible write and read in Socket , and its usefull for me

Sorry for my english

**Comment by nerai** [comment]
@shargon There are related tickets (#27, #37) which were closed. However, I will reconsider them. In particular, QuickLog (another library I wrote, not open source yet) seems like a viable option - it would use pretty much exactly the interface you described.

**Comment by nerai** [comment]
https://github.com/nerai/Unlog

**Comment by nerai** [comment]
Must be done without Unlog, would be too closely tied together. Instead, use hookable output events.
