### ISSUE TITLE
Questions: sub-menus, 'help' in a submenu, and providing common commands to multiple submenus

### ISSUE THREAD

**Issue by JohnVolkar** [nerai/CMenu#93]
This looks like a great library, and I started to try to use it for what will be a fairly a complex project.  We will have _lots_ of commands, and want to allow our SQA group to use this to script things (and don't want to go the route of a full blown DSL).  I have two questions/hurdles that I've bumped into and would like to pick your brain before rummaging the code base.

The first hurdle I have right now is organizing all the commands, and it appeared that the sub-menu example would do the trick nicely.   To test this, I've setup two submenus (UsrMenu and DevMenu) and added a few commands to each.  I have my MainMenu and add the two subs to it.  Everything works great, except that I cannot get help about the commands within each of the submenus.  
$ usr  
user$ help 
This gives help on the usr command itself, but doesn't list the commands which were added to that submenu.  Any idea if this should work?  Or how to accomplish it?  Do I need to maybe define my own 'help' command in each of the sub menus?

The second wrinkle I found is that I wanted to define a set of common commands to be available across all sub menus (we will eventually have many), and I thought to create a BaseMenu that would define them and have the submenus extend from BaseMenu to inherit them.  I've resorted to having the the BaseMenu expose an AddBaseCommands(CMenu targetMenu) operation and each child asks the base to add them directly.  This works, but it was a little surprise that 'inherited' menu items didn't just work.

Any help that you can give on the help on sub-menus topic would be welcomed.

**Comment by nerai** [comment]
Thank you for trying the library!

These are good questions, and I've just looked into the first issue you describe. I'm not sure, but I think I [fixed](https://github.com/nerai/CMenu/issues/79) something [similar](https://github.com/nerai/CMenu/issues/66) recently, but it is not yet in the latest release tag (0.7.1) which I suppose you're using. I've just added [a new tag 0.8 preview](https://github.com/nerai/CMenu/releases/tag/0.8_preview), which include this fix.

To make sure I understood you correctly, can you have a look at the following code to see if it reflects your scenario? I've included the output, which seems fine to me, and is probably what you wanted.

```
var main = new CMenu ();
var m1 = new CMenu ("1");
var m2 = new CMenu ("2");
main.Add (m1);
main.Add (m2);
m1.Add ("a", "This is the help text of 'a'.");
m1.Add ("b", "This is the help text of 'b'.");
m2.Add ("x");
m2.Add ("y");
main.Run ();
```

```
$ help
Available commands:
      1
      2
h   | help
q   | quit
Type "help <command>" for individual command help.
$ 1
$ help
Available commands:
      a
      b
h   | help
q   | quit
Type "help <command>" for individual command help.
$ help a
This is the help text of 'a'.
$ quit
$ help 1
      a
      b
h   | help
q   | quit
```

I'm currently looking into your second issue and will write here again later.

**Comment by nerai** [comment]
Re your second issue, does this code reflect your scenario?

```
class BaseMenu : CMenu
{
    public BaseMenu ()
    {
        Add ("time", s => Console.WriteLine ("Shared command in BaseMenu: " + DateTime.Now));
    }
}

class InheritedMenu : BaseMenu
{
    public InheritedMenu ()
    {
        Selector = "inherited";
        Add ("foo", s => Console.WriteLine ("InheritedMenu: foo"));
        Add ("bar", s => Console.WriteLine ("InheritedMenu: bar"));
    }
}

class Test
{
    static void Main (string[] args)
    {
        var main = new BaseMenu ();
        main.Add (new InheritedMenu ());
        main.Run ();
    }
}
```

Using the 0.8 preview tag, I get this output:

```
$ time
Shared command in BaseMenu: 2016.07.31 19:24:06
$ inherited
$ time
Shared command in BaseMenu: 2016.07.31 19:24:15
$ bar
InheritedMenu: bar
$
```

If I misunderstood, could you show an example of how you tried it earlier when it did not work?

**Comment by nerai** [comment]
@JVolkar , I hope that solved your problem. I'll close this ticket in a few days, unless I can help further.
