### ISSUE TITLE
Let's publish on Nuget!

### ISSUE THREAD

**Issue by MrVine** [nerai/CMenu#95]
Hello, @nerai !
I found this library, and I think that it can be useful for other developers (as for me), but I can't install it via `NuGet Package Manager`. What about publish it on `NuGet`?
I can do it, but it is your library, so I want you to publish this library - it is awesome :)

**Comment by nerai** [comment]
Hello @MrVine !
Thank you so much for the kind words, I'm happy that it is useful.
I will look into putting it on NuGet today. I have no experience with publishing on NuGet yet, so it may take a short while, but I've long wanted to try and do it :)

**Comment by nerai** [comment]
It should now be live at https://www.nuget.org/packages/NConsoleMenu. Thank you again for nudging me to do this!

I noticed a couple minor cosmetic issues with the current release, I will fix those soon. If you have any hints or suggestions what should be improved in particular regarding Nuget, I'd be happy to hear, too!

**Comment by MrVine** [comment]
Hello @nerai !
Thank you so much for publish this project on NuGet!
From time to time I write small console applications, and always I should create menu by my own. But now (thanks for you) I will save my time and just use your library!
Unfortunately I have a lot of work now, but when I will have a time I know the best candidacy to contribute on GitHub ;-)

**Comment by nerai** [comment]
@MrVine that's good to know, happy for you! Thank you again :+1:
